### ISSUE TITLE
Will Not Run in Unraid

### ISSUE THREAD

**Issue by xKOBAYASHIMARUx** [frncsdrk/avatar#14]
Hey, not entirely sure what the issue is but it looks like there may be a few things missing from the community apps docker image?

This may not be an issue but I did notice that there are no volume mappings. So no Avatar folder gets created within appdata and hence no configs where I'd expect to see some.

Main issue is the container won't start. The following is the complete log when trying to run:

No YAML parser loaded.  Suggest adding js-yaml dependency to your package.json file.
WARNING: No configurations found in configuration directory:/app/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/app/node_modules/config/lib/config.js:181
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "service.server.port" is not defined
    at Config.get (/app/node_modules/config/lib/config.js:181:11)
    at Object.start (/app/src/app.js:24:36)
    at Object.<anonymous> (/app/bin/www:5:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

> avatar@1.5.10 start
> node bin/www

**Comment by nwithan8** [comment]
Hello, author of the Unraid template here. I've been notified by a couple people about this same issue, that it seems the app is looking for a config file that is not present. I believe mapping the `/app/config` directory and adding the [`default.yml`](https://github.com/frncsdrk/avatar/blob/main/config/default.yml) in there might fix the issue; I'm going to test it now and if it seems to work, I'll update the template accordingly.

I was modeling the template off the Docker Compose files in this repository, which don't indicate needing to map any directories. Can you please clarify if/which directories need to be mapped between the host and the container?

EDIT: I was able to get Avatar to start by making a `default.json` equivalent of the `default.yml` file in a mapped `/app/config` directory, at which point the `http://[IP]:9000/avatar` endpoint works properly. I will update my template accordingly. @xKOBAYASHIMARUx The updated template with instructions on setting up the config file should populate and be available on the Community Apps Store within a few hours.

**Comment by frncsdrk** [comment]
@xKOBAYASHIMARUx Thank you for taking the time to report this issue. You found a bug caused by a missing dependency, which was not visible with a local installation.
I fixed the issue and created a patch release.

@nwithan8 First of all, thank you for creating an Unraid Community App for this service and stepping in to provide a workaround for this issue. I appreciate it.
But I'd like to use this opportunity to bring up a few points for your consideration.
I was fairly surprised to find an issue about the service related to its usage with Unraid in my inbox. The explanation being, that I simply didn't know about it. That's fine, of course. This service is free and open source and is intended to be for whoever has a use for it. That being said, what got me a little perplexed is that the community app directly references this repository and its issue tracker, implying that the CA is originating from this repository or its authors, which is not the case.
In my opinion, [`Support`](https://github.com/nwithan8/unraid_templates/blob/main/templates/avatar.xml#L13) should point to the issue tracker of the template repository, especially if you didn't at least leave the maintainer of the project a message beforehand to inform them about its usage. Currently, I cannot offer dedicated support for issues that might arise from its usage with Unraid.
Another thing I have to bring up is the state the template was published in. If there was any kind of testing, I'm sure the problem reported in this issue would have been fairly obvious. That is also in part caused by the lack in upkeep regarding the container image of the service. I won't dispute that. But the intention of the `Dockerfile` and `docker-compose` config is mainly for convenience and to provide a starting point for a production setup. In other words, executing `docker run <container>` is a good idea before publishing a CA for Unraid or something similar.
Last but not least, you seem to use the [`latest`-Tag in your template](https://github.com/nwithan8/unraid_templates/blob/main/templates/avatar.xml#L4). Since you answered this issue before me, I assume you watch this repository for changes. I would recommend to explicitly specify a tag like `1.5.11` instead and updating the template if there is a new release, and you had time to test it. Otherwise, new bugs might make it to the end-user without you even noticing, and it could also pose a potential security risk. Food for thought.

**Comment by nwithan8** [comment]
You bring up some fair points. I apologize for not detecting this error during testing of the template and causing users to open tickets on this repository.

That said, Unraid templates are largely just Docker Compose but for the Unraid GUI. More likely than not, any issue a user would face with an application would be due to the application/source code itself, not the Docker configuration of said application. Therefore, it makes more sense for the "Support" link of an application to point to the upstream project; there is a dedicated support thread on the Unraid forums where users can get in touch with me to report template-related issues for any application.

> I would recommend to explicitly specify a tag like 1.5.11 instead and updating the template if there is a new release and you had time to test it. Otherwise new bugs might make it to the end-user without you even noticing and it could also pose a potential security risk.

Unfortunately, that's not how Unraid templates work. The templates themselves don't get auto-updated, only if a user were to manually uninstall and reinstall an application template from the Community Apps Store. Me making a change to a template would likely not populate to most users post-installation on their systems. The CA Store plugin on Unraid does, however, accommodate checking for updates to the Docker image of each respective application/container, which is why most apps simply point to the `latest` tag for the Docker image to auto-update the image itself if a new update is available. And while I do try to keep up with all the apps I have templatized, I have published over 100 templates on the CA Store, so it would be virtually impossible for me to monitor and update templates accordingly for each application (barring actual changes to Docker environmental variables, paths, ports, etc.).

**Comment by xKOBAYASHIMARUx** [comment]
First off, thanks all for your time. Sincere apologies for causing any issues with this this thread going to the improper peoples.

@nwithan8 I did get it working but I think there are still missing parts from the container template in the unraid CA. It looks like it was indeed updated but there are no additional instructions. I also had to manually create a folder in appdata and manually map it to the Avatar container. One quick note about mapping, it should map "/config" not "/app/config", but once I did that, created a default.json file, pasted the contents you linked with the default.yml file, then it booted up properly. 

One other caveat, the unraid container "WebUI" is linked to the wrong address. It's currently linked to "http://[IP]:9000" but needs linked to "http://[IP]:9000/avatar" in order to work.

*EDIT: Ah, I finally understand how this works. So the WebUI link is correct but to pass in commands you use what follows after the address in a web browser. Ie "http://[IP]:9000/avatar" creates a default avatar generated from default values whereas "http://[IP]:9000/avatar/random" generates one with a random set of values in its parameters. List of commands found at https://frncsdrk.github.io/avatar/#api-Avatar-CreateAvatar

I have some decent experience now being dangerous and installing various apps and containers within Unraid though I won't pretend to be an expert and certainly don't have a vast knowledge regarding docker/containers/internal networking. I very much appreciate everyone's time and want to thank all for helping.

> Hello, author of the Unraid template here. I've been notified by a couple people about this same issue, that it seems the app is looking for a config file that is not present. I believe mapping the `/app/config` directory and adding the [`default.yml`](https://github.com/frncsdrk/avatar/blob/main/config/default.yml) in there might fix the issue; I'm going to test it now and if it seems to work, I'll update the template accordingly.
> 
> I was modeling the template off the Docker Compose files in this repository, which don't indicate needing to map any directories. Can you please clarify if/which directories need to be mapped between the host and the container?
> 
> EDIT: I was able to get Avatar to start by making a `default.json` equivalent of the `default.yml` file in a mapped `/app/config` directory, at which point the `http://[IP]:9000/avatar` endpoint works properly. I will update my template accordingly. @xKOBAYASHIMARUx The updated template with instructions on setting up the config file should populate and be available on the Community Apps Store within a few hours.

**Comment by frncsdrk** [comment]
@nwithan8 Thank you for considering the points I made and for clarifying the functionality of CAs in Unraid. To offer an alternative to the `latest` tag, I added a `stable` tag, which is only built and pushed when tags are created in the repository. This should cover all your points about maintainability and how Unraid handles CA updates.
I hope this will convince you to move away from the `latest` tag and potentially unstable changes. It might also be something you want to check for or discuss with the authors of other services you maintain the CAs for.

@xKOBAYASHIMARUx I also implemented a fallback for the port in case the config is missing or is in the wrong place. This should definitely make a custom configuration for the Unraid CA unnecessary.
A custom configuration shouldn't have been necessary from the start, since a default config is present in the image. The bug you found was caused by the service not being able to parse the configuration file.
You might be onto something if you say the mount point might need to be changed. Currently, the mount might override the default configuration. Unfortunately, I cannot verify that assumption and I couldn't gather enough information from the sparse documentation about CAs to provide more pointers. 
Though to be clear, the [mount point configured in the template](https://github.com/nwithan8/unraid_templates/blob/main/templates/avatar.xml#L38) is an absolute path which I would expect to work. But that is something to be investigated further by @nwithan8.

**Comment by nwithan8** [comment]
I was able to get the app working perfectly with the template as written. Looking at @xKOBAYASHIMARUx 's comment, it sounds like their template did not get updated automatically (as I said earlier, you would need to completely uninstall and reinstall the app from the Apps Store, and even then, it might be continuing to use the cached template due to how the CA plugin stores templates on the host system).

I will update the template to point to the stable tag so that future installers hopefully won't run into these issues

**Comment by frncsdrk** [comment]
@nwithan8 Thanks for testing the changes.

@xKOBAYASHIMARUx As @nwithan8 mentioned, please try reinstalling the app. Since the service is stateless, this shouldn't be problematic.

I'll close the issue for now as I consider the bug fixed.
